FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.10 AS builder
WORKDIR /go/src/github.com/openshift/node-problem-detector-operator
COPY . .
RUN GO111MODULE=off go build ./cmd/node-problem-detector-operator

FROM registry.ci.openshift.org/ocp/4.10:base
COPY --from=builder /go/src/github.com/openshift/node-problem-detector-operator/node-problem-detector-operator /usr/bin/
