FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-openshift-4.6 AS builder
WORKDIR /go/src/github.com/openshift/node-problem-detector-operator
COPY . .
RUN go build ./cmd/node-problem-detector-operator

FROM registry.svc.ci.openshift.org/ocp/4.6:base
COPY --from=builder /go/src/github.com/openshift/node-problem-detector-operator/node-problem-detector-operator /usr/bin/
