// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeProblemDetector) DeepCopyInto(out *NodeProblemDetector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeProblemDetector.
func (in *NodeProblemDetector) DeepCopy() *NodeProblemDetector {
	if in == nil {
		return nil
	}
	out := new(NodeProblemDetector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeProblemDetector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeProblemDetectorList) DeepCopyInto(out *NodeProblemDetectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeProblemDetector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeProblemDetectorList.
func (in *NodeProblemDetectorList) DeepCopy() *NodeProblemDetectorList {
	if in == nil {
		return nil
	}
	out := new(NodeProblemDetectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeProblemDetectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeProblemDetectorSpec) DeepCopyInto(out *NodeProblemDetectorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeProblemDetectorSpec.
func (in *NodeProblemDetectorSpec) DeepCopy() *NodeProblemDetectorSpec {
	if in == nil {
		return nil
	}
	out := new(NodeProblemDetectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeProblemDetectorStatus) DeepCopyInto(out *NodeProblemDetectorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeProblemDetectorStatus.
func (in *NodeProblemDetectorStatus) DeepCopy() *NodeProblemDetectorStatus {
	if in == nil {
		return nil
	}
	out := new(NodeProblemDetectorStatus)
	in.DeepCopyInto(out)
	return out
}
